apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: test-prov-shoot-spec-storage
  namespace: kcp-system
spec:
  volumeSnapshotClassName: kim-shoot-dump
  source:
    persistentVolumeClaimName: test-prov-shoot-spec-storage
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: test-kim-shoot-spec-storage
  namespace: kcp-system
spec:
  volumeSnapshotClassName: kim-shoot-dump
  source:
    persistentVolumeClaimName: test-kim-shoot-spec-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-prov-shoot-read-only
  namespace: kcp-system
spec:
  storageClassName: standard-rwo
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: test-prov-shoot-spec-storage
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-kim-shoot-read-only
  namespace: kcp-system
spec:
  storageClassName: standard-rwo
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: test-kim-shoot-spec-storage
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi