apiVersion: v1
kind: ConfigMap
metadata:
  name: converter-config
data:
  converter_config.json: |
    {
      "kubernetes": {
        "defaultVersion": "1.29",
        "enableKubernetesVersionAutoUpdate": true,
        "enableMachineImageVersionAutoUpdate": false
      },
      "dns": {
        "secretName": "aws-route53-secret-dev",
        "domainPrefix": "dev.kyma.ondemand.com",
        "providerType": "aws-route53"
      },
      "aws": {
        "enableIMDSv2": "true"
      },
      "gardener": {
        "projectName": "kyma-dev"
      },
      "machineImage": {
        "defaultVersion": "1312.3.0"
      }
    }
      
