# permissions for end users to edit clusterinventories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clusterinventory-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-inventory
    app.kubernetes.io/part-of: cluster-inventory
    app.kubernetes.io/managed-by: kustomize
  name: clusterinventory-editor-role
rules:
- apiGroups:
  - clusterinventory.kyma-project.io
  resources:
  - clusterinventories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clusterinventory.kyma-project.io
  resources:
  - clusterinventories/status
  verbs:
  - get
