apiVersion: infrastructuremanager.kyma-project.io/v1
kind: Runtime
metadata:
  labels:
    kyma-project.io/controlled-by-provisioner: "false"
    kyma-project.io/instance-id: instance-id
    kyma-project.io/runtime-id: runtime-id
    kyma-project.io/broker-plan-id: plan-id
    kyma-project.io/broker-plan-name: plan-name
    kyma-project.io/global-account-id: global-account-id
    kyma-project.io/subaccount-id: subAccount-id
    kyma-project.io/shoot-name: aws-minimal
    kyma-project.io/region: region
    operator.kyma-project.io/kyma-name: kymaName
  name: aws-minimal
  namespace: kcp-system
spec:
  shoot:
    # spec.shoot.name is required
    name: aws-minimal
    # spec.shoot.purpose is required
    purpose: production
    # spec.shoot.region is required
    region: eu-central-1
    # spec.shoot.platformRegion is required
    platformRegion: "cf-eu11"
    # spec.shoot.secretBindingName is required
    secretBindingName: "hyperscaler secret"
    kubernetes:
      kubeAPIServer:
        # spec.shoot.kubernetes.kubeAPIServer.oidcConfig is required
        oidcConfig:
          clientID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
          groupsClaim: groups
          issuerURL: https://my.cool.tokens.com
          signingAlgs:
            - RS256
          usernameClaim: sub
    provider:
      # spec.shoot.provider.type is required
      type: aws
      # spec.shoot.provider.workers is required
      workers:
        - machine:
            # spec.shoot.workers.machine.type is required
            type: m6i.large
            image:
              name: gardenlinux
              version: 1443.9.0
          name: "worker-0"
          # spec.shoot.workers.zones is required
          zones:
            - eu-central-1a
            - eu-central-1b
            - eu-central-1c
          # spec.shoot.workers.minimum is required
          minimum: 3
          # spec.shoot.workers.maximum is required
          maximum: 20
          # spec.shoot.workers.maxSurge is required in the first release.
          # It can be optional in the future, as it equals to zone count
          maxSurge: 3
          # spec.shoot.workers.maxUnavailable is required in the first release.
          # It can be optional in the future, as it is always set to 0
          maxUnavailable: 0
          # spec.shoot.workers.volume is required for the first release
          # Probably can be moved into KIM, as it is hardcoded in KEB, and not dependent on plan
          volume:
            type: gp2
            size: 50Gi
    # spec.shoot.Networking is required
    networking:
      type: calico
      pods: 100.64.0.0/12
      nodes: 10.250.0.0/16
      services: 100.104.0.0/13
    # spec.shoot.controlPlane is required
    controlPlane:
      highAvailability:
        failureTolerance:
          type: node
  security:
    networking:
      filter:
        # spec.security.networking.filter.egress.enabled is required
        egress:
          enabled: false
    # spec.security.administrators is required
    administrators:
      - admin@myorg.com