apiVersion: infrastructuremanager.kyma-project.io/v1
kind: Runtime
metadata:
  labels:
    kyma-project.io/controlled-by-provisioner: "false"
    kyma-project.io/instance-id: instance-id
    kyma-project.io/runtime-id: runtime-id
    kyma-project.io/broker-plan-id: plan-id
    kyma-project.io/broker-plan-name: plan-name
    kyma-project.io/global-account-id: global-account-id
    kyma-project.io/subaccount-id: subAccount-id
    kyma-project.io/shoot-name: ops-full
    kyma-project.io/region: region
    operator.kyma-project.io/kyma-name: kymaName
  name: ops-full
  namespace: kcp-system
spec:
  shoot:
    # spec.shoot.name is required
    name: ops-full
    # spec.shoot.purpose is required
    purpose: production
    # spec.shoot.region is required
    region: eu-de-1
    # spec.shoot.platformRegion is required
    platformRegion: "cf-eu11"
    # spec.shoot.secretBindingName is required
    secretBindingName: "hyperscaler secret"
    # spec.shoot.enforceSeedLocation is optional ; it allows to make sure the seed cluster will be located in the same region as the runtime
    enforceSeedLocation: "true"
    kubernetes:
      # spec.shoot.kubernetes.version is optional, when not provided default will be used
      version: "1.28.7"
      kubeAPIServer:
        # spec.shoot.kubernetes.kubeAPIServer.oidcConfig is required
        oidcConfig:
          clientID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
          groupsClaim: groups
          issuerURL: https://my.cool.tokens.com
          signingAlgs:
            - RS256
          usernameClaim: sub
        # spec.shoot.kubernetes.kubeAPIServer.additionalOidcConfig is optional, not implemented in the first KIM release
        additionalOidcConfig:
          - clientID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
            groupsClaim: groups
            issuerURL: https://some.others.tokens.com
            signingAlgs:
              - RS256
            usernameClaim: sub
            usernamePrefix: 'someother'
    # spec.shoot.provider is required
    provider:
      # spec.shoot.provider.type is required
      type: openstack
      # spec.shoot.provider.workers is required
      workers:
        - machine:
            # spec.shoot.workers.machine.type is required
            type: g_c2_m8
            # spec.shoot.workers.machine.image is optional, when not provider default will be used
            # Will be modified by the SRE
            image:
              name: gardenlinux
              version: 1443.9.0
          # Note: KEB doesn't specify the volume, Gardener defaults used
          # spec.shoot.workers.zones is optional
          zones:
            - eu-de-1a
            - eu-de-1b
            - eu-de-1d
          # spec.shoot.workers.name is optional, if not provided default will be used
          name: cpu-worker-0
          # spec.shoot.workers.minimum is required
          minimum: 3
          # spec.shoot.workers.maximum is required
          maximum: 20
          # spec.shoot.workers.maxSurge is required in the first release.
          # It can be optional in the future, as it equals to zone count
          maxSurge: 3
          # spec.shoot.workers.maxUnavailable is required in the first release.
          # It can be optional in the future, as it is always set to 0
          maxUnavailable: 0
    # spec.shoot.Networking is required
    networking:
      type: calico
      pods: 10.96.0.0/13
      nodes: 10.250.0.0/22
      services: 10.104.0.0/13
    # spec.shoot.controlPlane is required
    controlPlane:
      highAvailability:
        failureTolerance:
          type: zone
  security:
    networking:
      filter:
        # spec.security.networking.filter.egress.enabled is required
        egress:
          enabled: false
        # spec.security.networking.filter.ingress.enabled is optional (default=false)
        ingress:
          enabled: true
    # spec.security.administrators is required
    administrators:
      - admin@myorg.com
