name: runtime-cleanup Build

on:
  push:
    branches:
      - main
    paths:
      - "hack/runtime-cleanup/**"
      - "!hack/runtime-cleanup/**/*.md"
  pull_request_target:
    types: [opened, synchronize]
    paths:
      - "hack/runtime-cleanup/**"
      - "!hack/runtime-cleanup/**/*.md"

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  build-image:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: runtime-cleanup
      dockerfile: Dockerfile
      context: hack/runtime-cleanup
      export-tags: false
